[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["node_modules/xmlhttprequest/lib/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
